imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_news.yml }
    - { resource: sonata/sonata_classification.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_notification.yml }
    - { resource: sonata/sonata_page.yml }
    - { resource: sonata/sonata_seo.yml }
    - { resource: sonata/sonata_admin.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator: { fallbacks: [en] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json:     Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        # The mappings to import the FOSMessage entities
        mappings:
            fos_message:
                type: annotation
                dir: %kernel.root_dir%/../vendor/friendsofsymfony/message/src/Driver/Doctrine/ORM/Entity
                prefix: FOS\Message\Driver\Doctrine\ORM\Entity

        # User your user entity instead of the PersonInterface
        resolve_target_entities:
            FOS\Message\Model\PersonInterface: Application\Sonata\UserBundle\Entity\User

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/admin', priorities: ['html', 'xhtml']}
            - { path: '^/login', priorities: ['html', 'xhtml']}
            - { path: '^/profile', priorities: ['html', 'xhtml']}
            - { path: '^/register', priorities: ['html', 'xhtml']}
            - { path: '^/api/doc', priorities: ['html', 'xhtml', 'json', 'xml']}
            - { path: '^/', priorities: ['json', 'xml']}
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener: force
    body_converter:
        enabled: true
        validate: true

fos_user:
    db_driver: orm
    firewall_name: api
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager


fos_oauth_server:
    db_driver: orm
    client_class: PoweredByMoe\ApiBundle\Entity\Client
    access_token_class: PoweredByMoe\ApiBundle\Entity\AccessToken
    refresh_token_class: PoweredByMoe\ApiBundle\Entity\RefreshToken
    auth_code_class: PoweredByMoe\ApiBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migrations
    name: Application Migrations

al_swagger_ui:
    static_resources:
        resource_dir: app/Resources/swagger-docs
        resource_list_filename:  api-docs.json
    resource_list: al_swagger_ui_static_resource_list

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

twig:
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

ivory_ck_editor:
    default_config: default
    configs:
        default:
            uiColor: "#000000"
            extraPlugin: "wordcount"
        news:
            toolbar:      standard